// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signature.proto

package backend // import "gitlab.ti.bfh.ch/hirtp1/thesis/backend"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Envelope struct {
	Sender               string            `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient            string            `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Message              *Envelope_Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_signature_d252a089a2c34b2e, []int{0}
}
func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (dst *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(dst, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Envelope) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Envelope) GetMessage() *Envelope_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Envelope_Message struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Time                 uint64   `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope_Message) Reset()         { *m = Envelope_Message{} }
func (m *Envelope_Message) String() string { return proto.CompactTextString(m) }
func (*Envelope_Message) ProtoMessage()    {}
func (*Envelope_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_signature_d252a089a2c34b2e, []int{0, 0}
}
func (m *Envelope_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope_Message.Unmarshal(m, b)
}
func (m *Envelope_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope_Message.Marshal(b, m, deterministic)
}
func (dst *Envelope_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope_Message.Merge(dst, src)
}
func (m *Envelope_Message) XXX_Size() int {
	return xxx_messageInfo_Envelope_Message.Size(m)
}
func (m *Envelope_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope_Message proto.InternalMessageInfo

func (m *Envelope_Message) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Envelope_Message) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Envelope_Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Envelope)(nil), "Envelope")
	proto.RegisterType((*Envelope_Message)(nil), "Envelope.Message")
}

func init() { proto.RegisterFile("signature.proto", fileDescriptor_signature_d252a089a2c34b2e) }

var fileDescriptor_signature_d252a089a2c34b2e = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0x5b, 0xba, 0x76, 0x44, 0xc4, 0x1c, 0x64, 0x11, 0x0f, 0xc5, 0x83, 0x2c, 0x08,
	0x59, 0xd4, 0x37, 0x10, 0x3c, 0x8a, 0x90, 0xa3, 0xb7, 0x24, 0x1d, 0x37, 0x83, 0xdd, 0x24, 0x24,
	0x53, 0x1f, 0xcf, 0x67, 0x93, 0x8d, 0x59, 0x7a, 0x9b, 0xef, 0xff, 0x87, 0xf9, 0x18, 0xb8, 0xca,
	0x34, 0x7a, 0xcd, 0xc7, 0x84, 0x32, 0xa6, 0xc0, 0xe1, 0xfe, 0xb7, 0x81, 0xf3, 0x37, 0xff, 0x83,
	0x87, 0x10, 0x51, 0xdc, 0xc0, 0x26, 0xa3, 0xdf, 0x63, 0xea, 0x9a, 0x5d, 0xd3, 0x6f, 0x55, 0x25,
	0x71, 0x07, 0xdb, 0x84, 0x96, 0x22, 0xa1, 0xe7, 0xee, 0xac, 0x54, 0xa7, 0x40, 0x3c, 0x42, 0x3b,
	0x61, 0xce, 0x7a, 0xc4, 0x6e, 0xb5, 0x6b, 0xfa, 0x8b, 0xe7, 0x6b, 0xb9, 0x5c, 0x94, 0xef, 0xff,
	0x85, 0x5a, 0x36, 0x6e, 0x3f, 0xa0, 0xad, 0xd9, 0x6c, 0xf3, 0xc7, 0xc9, 0x54, 0xdb, 0xa5, 0xaa,
	0x24, 0x04, 0xac, 0x99, 0x26, 0x2c, 0xa2, 0xb5, 0x2a, 0xb3, 0xe8, 0xa0, 0xb5, 0xc1, 0xf3, 0xec,
	0x5f, 0x15, 0xff, 0x82, 0xaf, 0xfd, 0xe7, 0xc3, 0x48, 0x7c, 0xd0, 0x46, 0x32, 0x49, 0xf3, 0xe5,
	0xa4, 0x75, 0x83, 0xa3, 0xc4, 0xf1, 0x69, 0x60, 0x87, 0x99, 0xf2, 0x60, 0xb4, 0xfd, 0x46, 0xbf,
	0x37, 0x9b, 0xf2, 0xf1, 0xcb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x1f, 0xfb, 0x9a, 0x04,
	0x01, 0x00, 0x00,
}
