// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signature.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MACAlgorithm int32

const (
	MACAlgorithm_HMAC_SHA2_256 MACAlgorithm = 0
	MACAlgorithm_HMAC_SHA2_512 MACAlgorithm = 1
	MACAlgorithm_HMAC_SHA3_256 MACAlgorithm = 2
	MACAlgorithm_HMAC_SHA3_512 MACAlgorithm = 3
	MACAlgorithm_POLY1305_AES  MACAlgorithm = 4
)

var MACAlgorithm_name = map[int32]string{
	0: "HMAC_SHA2_256",
	1: "HMAC_SHA2_512",
	2: "HMAC_SHA3_256",
	3: "HMAC_SHA3_512",
	4: "POLY1305_AES",
}
var MACAlgorithm_value = map[string]int32{
	"HMAC_SHA2_256": 0,
	"HMAC_SHA2_512": 1,
	"HMAC_SHA3_256": 2,
	"HMAC_SHA3_512": 3,
	"POLY1305_AES":  4,
}

func (x MACAlgorithm) String() string {
	return proto.EnumName(MACAlgorithm_name, int32(x))
}
func (MACAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_signature_43bf4d55a2aacf73, []int{0}
}

type HashAlgorithm int32

const (
	HashAlgorithm_SHA2_256 HashAlgorithm = 0
	HashAlgorithm_SHA2_512 HashAlgorithm = 1
	HashAlgorithm_SHA3_256 HashAlgorithm = 2
	HashAlgorithm_SHA3_512 HashAlgorithm = 3
)

var HashAlgorithm_name = map[int32]string{
	0: "SHA2_256",
	1: "SHA2_512",
	2: "SHA3_256",
	3: "SHA3_512",
}
var HashAlgorithm_value = map[string]int32{
	"SHA2_256": 0,
	"SHA2_512": 1,
	"SHA3_256": 2,
	"SHA3_512": 3,
}

func (x HashAlgorithm) String() string {
	return proto.EnumName(HashAlgorithm_name, int32(x))
}
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_signature_43bf4d55a2aacf73, []int{1}
}

type SignatureLevel int32

const (
	SignatureLevel_ADVANCED  SignatureLevel = 0
	SignatureLevel_QUALIFIED SignatureLevel = 1
)

var SignatureLevel_name = map[int32]string{
	0: "ADVANCED",
	1: "QUALIFIED",
}
var SignatureLevel_value = map[string]int32{
	"ADVANCED":  0,
	"QUALIFIED": 1,
}

func (x SignatureLevel) String() string {
	return proto.EnumName(SignatureLevel_name, int32(x))
}
func (SignatureLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_signature_43bf4d55a2aacf73, []int{2}
}

type SignatureData struct {
	SaltedDocumentHash [][]byte       `protobuf:"bytes,1,rep,name=salted_document_hash,json=saltedDocumentHash,proto3" json:"salted_document_hash,omitempty"`
	HashAlgorithm      HashAlgorithm  `protobuf:"varint,2,opt,name=hash_algorithm,json=hashAlgorithm,proto3,enum=HashAlgorithm" json:"hash_algorithm,omitempty"`
	MacKey             []byte         `protobuf:"bytes,3,opt,name=mac_key,json=macKey,proto3" json:"mac_key,omitempty"`
	MacAlgorithm       MACAlgorithm   `protobuf:"varint,4,opt,name=mac_algorithm,json=macAlgorithm,proto3,enum=MACAlgorithm" json:"mac_algorithm,omitempty"`
	SignatureLevel     SignatureLevel `protobuf:"varint,5,opt,name=signature_level,json=signatureLevel,proto3,enum=SignatureLevel" json:"signature_level,omitempty"`
	IdToken            []byte         `protobuf:"bytes,6,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	JwkIdp             []byte         `protobuf:"bytes,7,opt,name=jwk_idp,json=jwkIdp,proto3" json:"jwk_idp,omitempty"`
	// maps the fingerprint of the jwk cert to its ltv information
	LtvIdp               map[string]*LTV `protobuf:"bytes,8,rep,name=ltv_idp,json=ltvIdp,proto3" json:"ltv_idp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SignatureData) Reset()         { *m = SignatureData{} }
func (m *SignatureData) String() string { return proto.CompactTextString(m) }
func (*SignatureData) ProtoMessage()    {}
func (*SignatureData) Descriptor() ([]byte, []int) {
	return fileDescriptor_signature_43bf4d55a2aacf73, []int{0}
}
func (m *SignatureData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureData.Unmarshal(m, b)
}
func (m *SignatureData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureData.Marshal(b, m, deterministic)
}
func (dst *SignatureData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureData.Merge(dst, src)
}
func (m *SignatureData) XXX_Size() int {
	return xxx_messageInfo_SignatureData.Size(m)
}
func (m *SignatureData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureData.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureData proto.InternalMessageInfo

func (m *SignatureData) GetSaltedDocumentHash() [][]byte {
	if m != nil {
		return m.SaltedDocumentHash
	}
	return nil
}

func (m *SignatureData) GetHashAlgorithm() HashAlgorithm {
	if m != nil {
		return m.HashAlgorithm
	}
	return HashAlgorithm_SHA2_256
}

func (m *SignatureData) GetMacKey() []byte {
	if m != nil {
		return m.MacKey
	}
	return nil
}

func (m *SignatureData) GetMacAlgorithm() MACAlgorithm {
	if m != nil {
		return m.MacAlgorithm
	}
	return MACAlgorithm_HMAC_SHA2_256
}

func (m *SignatureData) GetSignatureLevel() SignatureLevel {
	if m != nil {
		return m.SignatureLevel
	}
	return SignatureLevel_ADVANCED
}

func (m *SignatureData) GetIdToken() []byte {
	if m != nil {
		return m.IdToken
	}
	return nil
}

func (m *SignatureData) GetJwkIdp() []byte {
	if m != nil {
		return m.JwkIdp
	}
	return nil
}

func (m *SignatureData) GetLtvIdp() map[string]*LTV {
	if m != nil {
		return m.LtvIdp
	}
	return nil
}

type LTV struct {
	Ocsp                 []byte   `protobuf:"bytes,1,opt,name=ocsp,proto3" json:"ocsp,omitempty"`
	Crl                  []byte   `protobuf:"bytes,2,opt,name=crl,proto3" json:"crl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LTV) Reset()         { *m = LTV{} }
func (m *LTV) String() string { return proto.CompactTextString(m) }
func (*LTV) ProtoMessage()    {}
func (*LTV) Descriptor() ([]byte, []int) {
	return fileDescriptor_signature_43bf4d55a2aacf73, []int{1}
}
func (m *LTV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LTV.Unmarshal(m, b)
}
func (m *LTV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LTV.Marshal(b, m, deterministic)
}
func (dst *LTV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LTV.Merge(dst, src)
}
func (m *LTV) XXX_Size() int {
	return xxx_messageInfo_LTV.Size(m)
}
func (m *LTV) XXX_DiscardUnknown() {
	xxx_messageInfo_LTV.DiscardUnknown(m)
}

var xxx_messageInfo_LTV proto.InternalMessageInfo

func (m *LTV) GetOcsp() []byte {
	if m != nil {
		return m.Ocsp
	}
	return nil
}

func (m *LTV) GetCrl() []byte {
	if m != nil {
		return m.Crl
	}
	return nil
}

type SignatureFile struct {
	// pkcs7 enveloped and signed,
	// containing CA chain,
	// and if ltv is enabled CRL and OCSP as well
	SignatureDataInPkcs7 []byte `protobuf:"bytes,1,opt,name=signature_data_in_pkcs7,json=signatureDataInPkcs7,proto3" json:"signature_data_in_pkcs7,omitempty"`
	// pkcs7 enveloped rfc3161 timestamp (not signed, just enveloped)
	// along with CA chain
	// and if ltv is enabled CRL and OCSP as well
	// each later timestamp authenticates a former one
	// thus forming a chain for archival
	Rfc3161InPkcs7       [][]byte `protobuf:"bytes,2,rep,name=rfc3161_in_pkcs7,json=rfc3161InPkcs7,proto3" json:"rfc3161_in_pkcs7,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureFile) Reset()         { *m = SignatureFile{} }
func (m *SignatureFile) String() string { return proto.CompactTextString(m) }
func (*SignatureFile) ProtoMessage()    {}
func (*SignatureFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_signature_43bf4d55a2aacf73, []int{2}
}
func (m *SignatureFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureFile.Unmarshal(m, b)
}
func (m *SignatureFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureFile.Marshal(b, m, deterministic)
}
func (dst *SignatureFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureFile.Merge(dst, src)
}
func (m *SignatureFile) XXX_Size() int {
	return xxx_messageInfo_SignatureFile.Size(m)
}
func (m *SignatureFile) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureFile.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureFile proto.InternalMessageInfo

func (m *SignatureFile) GetSignatureDataInPkcs7() []byte {
	if m != nil {
		return m.SignatureDataInPkcs7
	}
	return nil
}

func (m *SignatureFile) GetRfc3161InPkcs7() [][]byte {
	if m != nil {
		return m.Rfc3161InPkcs7
	}
	return nil
}

func init() {
	proto.RegisterType((*SignatureData)(nil), "SignatureData")
	proto.RegisterMapType((map[string]*LTV)(nil), "SignatureData.LtvIdpEntry")
	proto.RegisterType((*LTV)(nil), "LTV")
	proto.RegisterType((*SignatureFile)(nil), "SignatureFile")
	proto.RegisterEnum("MACAlgorithm", MACAlgorithm_name, MACAlgorithm_value)
	proto.RegisterEnum("HashAlgorithm", HashAlgorithm_name, HashAlgorithm_value)
	proto.RegisterEnum("SignatureLevel", SignatureLevel_name, SignatureLevel_value)
}

func init() { proto.RegisterFile("signature.proto", fileDescriptor_signature_43bf4d55a2aacf73) }

var fileDescriptor_signature_43bf4d55a2aacf73 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x53, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x8d, 0x31, 0x01, 0x32, 0xd8, 0x8e, 0xbb, 0x8a, 0x14, 0x97, 0x13, 0xe2, 0x64, 0x51, 0xd5,
	0x0a, 0x46, 0xa4, 0x51, 0x2f, 0x95, 0x0b, 0xa4, 0xa0, 0x3a, 0x6d, 0x6a, 0x28, 0x52, 0x7b, 0x59,
	0x6d, 0xed, 0x4d, 0x70, 0x30, 0xb6, 0x65, 0x2f, 0x44, 0x7c, 0x52, 0xff, 0xb2, 0xda, 0x05, 0x8a,
	0x7d, 0x9b, 0xf7, 0xde, 0xcc, 0xf3, 0xcc, 0xec, 0x18, 0x2e, 0xf3, 0xf0, 0x39, 0x26, 0x6c, 0x93,
	0x51, 0x2b, 0xcd, 0x12, 0x96, 0x74, 0xfe, 0xca, 0xa0, 0xce, 0x8e, 0xdc, 0x88, 0x30, 0x82, 0x6e,
	0xe0, 0x2a, 0x27, 0x11, 0xa3, 0x01, 0x0e, 0x12, 0x7f, 0xb3, 0xa6, 0x31, 0xc3, 0x4b, 0x92, 0x2f,
	0x0d, 0xa9, 0x2d, 0x9b, 0x8a, 0x87, 0xf6, 0xda, 0xe8, 0x20, 0x4d, 0x48, 0xbe, 0x44, 0x03, 0xd0,
	0x78, 0x06, 0x26, 0xd1, 0x73, 0x92, 0x85, 0x6c, 0xb9, 0x36, 0x2a, 0x6d, 0xc9, 0xd4, 0x6c, 0xcd,
	0xe2, 0xb2, 0x73, 0x64, 0x3d, 0x75, 0x59, 0x84, 0xe8, 0x1a, 0xea, 0x6b, 0xe2, 0xe3, 0x15, 0xdd,
	0x19, 0x72, 0x5b, 0x32, 0x15, 0xaf, 0xb6, 0x26, 0xfe, 0x57, 0xba, 0x43, 0x36, 0xa8, 0x5c, 0x38,
	0xd9, 0x55, 0x85, 0x9d, 0x6a, 0x3d, 0x38, 0xc3, 0x93, 0x9b, 0xb2, 0x26, 0xfe, 0xc9, 0xec, 0xae,
	0x30, 0x1a, 0x8e, 0xe8, 0x96, 0x46, 0xc6, 0xb9, 0xa8, 0xba, 0xb4, 0xfe, 0x8f, 0xe7, 0x72, 0xda,
	0xd3, 0xf2, 0x12, 0x46, 0x6f, 0xa1, 0x11, 0x06, 0x98, 0x25, 0x2b, 0x1a, 0x1b, 0x35, 0xd1, 0x47,
	0x3d, 0x0c, 0xe6, 0x1c, 0xf2, 0x0e, 0x5f, 0x5e, 0x57, 0x38, 0x0c, 0x52, 0xa3, 0xbe, 0xef, 0xf0,
	0xe5, 0x75, 0x35, 0x0d, 0x52, 0xd4, 0x87, 0x7a, 0xc4, 0xb6, 0x42, 0x68, 0xb4, 0x65, 0xb3, 0x69,
	0xb7, 0xac, 0xd2, 0x12, 0x2d, 0x97, 0x6d, 0xa7, 0x41, 0x3a, 0x8e, 0x59, 0xb6, 0xf3, 0x6a, 0x91,
	0x00, 0xad, 0x4f, 0xd0, 0x2c, 0xd0, 0x48, 0x07, 0x99, 0x8f, 0x2e, 0xb5, 0x25, 0xf3, 0xc2, 0xe3,
	0x21, 0x6a, 0xc1, 0xf9, 0x96, 0x44, 0x1b, 0x2a, 0xd6, 0xd7, 0xb4, 0xab, 0x96, 0x3b, 0x5f, 0x78,
	0x7b, 0xea, 0x63, 0xe5, 0x4e, 0xea, 0xbc, 0x03, 0xd9, 0x9d, 0x2f, 0x10, 0x82, 0x6a, 0xe2, 0xe7,
	0xa9, 0xa8, 0x54, 0x3c, 0x11, 0x73, 0x33, 0x3f, 0x8b, 0x44, 0xa1, 0xe2, 0xf1, 0xb0, 0x93, 0x16,
	0xde, 0xf5, 0x3e, 0x8c, 0x28, 0x1a, 0xc0, 0xf5, 0x69, 0x43, 0x01, 0x61, 0x04, 0x87, 0x31, 0x4e,
	0x57, 0x7e, 0xfe, 0xe1, 0xe0, 0x74, 0x95, 0x17, 0x47, 0x98, 0xc6, 0x8f, 0x5c, 0x43, 0x26, 0xe8,
	0xd9, 0x93, 0xdf, 0xef, 0xdd, 0xf6, 0x4e, 0xf9, 0x15, 0x71, 0x0a, 0xda, 0x81, 0x3f, 0x64, 0x76,
	0x23, 0x50, 0x8a, 0x0f, 0x84, 0xde, 0x80, 0x3a, 0x79, 0x70, 0x86, 0x78, 0x36, 0x71, 0x6c, 0x6c,
	0x0f, 0x6e, 0xf5, 0xb3, 0x32, 0x35, 0xe8, 0xd9, 0xba, 0x54, 0xa4, 0xfa, 0x22, 0xab, 0x52, 0xa6,
	0x78, 0x96, 0x8c, 0x74, 0x50, 0x1e, 0xbf, 0xbb, 0xbf, 0x7a, 0xfd, 0x9b, 0x01, 0x76, 0xc6, 0x33,
	0xbd, 0xda, 0xfd, 0x02, 0x6a, 0xe9, 0xba, 0x90, 0x02, 0x8d, 0xc2, 0x97, 0x8e, 0x68, 0xff, 0x91,
	0x3d, 0x3a, 0xfa, 0x1f, 0x91, 0xb0, 0xee, 0xbe, 0x07, 0xad, 0x7c, 0x21, 0x5c, 0x77, 0x46, 0x0b,
	0xe7, 0xdb, 0x70, 0x3c, 0xd2, 0xcf, 0x90, 0x0a, 0x17, 0x3f, 0x7e, 0x3a, 0xee, 0xf4, 0x7e, 0x3a,
	0x1e, 0xe9, 0xd2, 0x67, 0xf8, 0xdd, 0xd8, 0xd2, 0x2c, 0x7c, 0x0a, 0x69, 0xf6, 0xa7, 0x26, 0xfe,
	0xa1, 0xfe, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x63, 0x78, 0xa1, 0x56, 0x03, 0x00, 0x00,
}
